version: "2.4"

services:
  nginx:
    ports:
      - "443:443"
    volumes:
      - ./nginx/conf.d/chainless-tls.conf:/etc/nginx/conf.d/chainless-tls.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
